# Generated by Django 6.1.1 on 2026-09-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_prioritylevel_coefficient_prioritylevel_name_and_more'),
        ('projects', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='terminated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='difficulty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='base.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='base.prioritylevel'),
        ),
    ]
