# Generated by Django 6.1.1 on 2026-09-30 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_prioritylevel_coefficient_prioritylevel_name_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.difficultylevel')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='tasks.task')),
                ('priority', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.prioritylevel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
