# Generated by Django 6.1.1 on 2026-09-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_prioritylevel_coefficient_prioritylevel_name_and_more'),
        ('tasks', '0007_alter_task_difficulty_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.prioritylevel'),
        ),
    ]
