# Generated by Django 6.1.1 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritylevel',
            name='coefficient',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='prioritylevel',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prioritylevel',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='difficultylevel',
            constraint=models.UniqueConstraint(fields=('name', 'coefficient'), name='unique_difficulty_level'),
        ),
        migrations.AddConstraint(
            model_name='prioritylevel',
            constraint=models.UniqueConstraint(fields=('name', 'coefficient'), name='unique_priority_level'),
        ),
    ]
